### ISSUE TITLE
Support for Austria

### ISSUE THREAD

**Issue by msonnberger** [worthbak/inventory-checker-app#1]
Would be nice if Austria‘s only Apple Store in Vienna could be added.

**Comment by worthbak** [comment]
Sure, that makes sense. Kärntner Straße is listed in the app, but Austrian store (`apple.com/at/...`) is missing. Thanks for raising the issue! I'll follow up.

**Comment by mbuchetics** [comment]
any update on this one?

**Comment by worthbak** [comment]
Added in v0.1.1 - apologies for the delay https://worthbak.github.io/inventory-checker-app/

**Comment by mbuchetics** [comment]
Thank you!!
