### ISSUE TITLE
New iPhone 15 models

### ISSUE THREAD

**Issue by BamesJond008** [worthbak/inventory-checker-app#112]
Hello!

Would it be possible to add the new iPhone 15 models as new products? 

Thanks!

**Comment by worthbak** [comment]
Support for the new iPhones will not be added to InventoryWatch 1.0, but will become available in InventoryWatch 2.0 next week, ahead of the in-store launch of this year's devices. If you haven't already, you can check out InventoryWatch 2.0 here: https://inventorywatch.app

**Comment by xgchen516** [comment]
looking forward to it!
earlier the better, as we can "pre order" pickup orders now

**Comment by BamesJond008** [comment]
Awesome, thank you! Definitely the sooner the better with some pre-orders slipping into November, I'm sure a lot of people are waiting to subscribe for SMS/email notifications :)
