### ISSUE TITLE
Additional SKU's request

### ISSUE THREAD

**Issue by Maybejames** [worthbak/inventory-checker-app#18]
Hi, I know this is probably an over used request. Would it be possible to update with some of the newer product SKU's?
In particular the new Studio hardware (Display and Mac).  Several different permutations even for the Monitor and it's going to be tough to get by the looks of it.
Thanks!

**Comment by worthbak** [comment]
Yeah, that's a good call - these new machines are a good reason to push out an update. I'll need to wait until it's clear which SKUs Apple intends to stock in-store, and I'm not sure that data is available yet. In any case, thanks for the suggestion! Stay tuned.

**Comment by Apple-MacMarcus** [comment]
Guess it is a safe bet that at least the standard configs will be in-stock.

If it helps, this is the SKU for the standard model: MJMV3LL/A

Mac Studio
32GB unified memory
512GB SSD storage
Front: Two USB-C ports, one SDXC card slot
Back: Four Thunderbolt 4 ports, two USB-A ports, one HDMI port, one 10Gb Ethernet port, one 3.5 mm headphone jack

**Comment by worthbak** [comment]
@Maybejames based on some initial data, it looks like Apple is stocking only two base configurations of the Mac Studio in-store - I've added these model numbers in a branch (linked above) and will cut a new release soon, once I can verify that there are no other in-store models the app should be tracking. 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/10028428/159022047-4bbce90a-d335-4fe8-a2bc-dad6551e17db.png">

**Comment by Maybejames** [comment]
Thanks, sorry I took some time to disconnect the past 10 days!
If I could find the Studio Display Product Codes, I'd also share. 
This is great much appreciated!

**Comment by worthbak** [comment]
Check out the latest release (`v0.0.4`) - I added both Mac Studio and Studio Display support over the weekend 👍 https://worthbak.github.io/inventory-checker-app/
