### ISSUE TITLE
Australia is misspelled 

### ISSUE THREAD

**Issue by dannolan** [worthbak/inventory-checker-app#24]
Refer to here, Australia is spelled as Austraiia, not Australia.

Thank you!

https://github.com/worthbak/inventory-checker-app/blob/0414d4ffd52115a347eb99ed5c576e72689f3591/InventoryWatch/Countries.swift#L32

**Comment by worthbak** [comment]
ahhh thanks for reporting that! I'll fix in the next build.

**Comment by worthbak** [comment]
This was fixed in a build earlier this spring - not sure why the issue itself wasn't closed.
