### ISSUE TITLE
Incorrect SKUs for 16-inch M1 Pro MBPs

### ISSUE THREAD

**Issue by KevinEmery** [worthbak/inventory-checker-app#28]
Just discovered this tool (thanks for putting it together and maintaining it!) and discovered that a few SKUs appear to be flipped for the baseline 16" machines

Specifically [these 4 lines](https://github.com/worthbak/inventory-checker-app/blob/80cb2669cddf8c81fb823f1c86d6cb44ab73e894/InventoryWatch/SKUData.swift#L133-L136) are swapped between the 512GB and the 1TB models. For example, MK183(country)/A is the model with the 512 GB SSD, not the 1TB as the file indicates. This is confirmed by looking up the individual model numbers as well as cross-checking what the tool reports as in stock against Apple's inventory on the store pages.

The problem appears to have been introduced in [this commit](https://github.com/worthbak/inventory-checker-app/commit/b81a79307aa075880e2fc4190605dbed14a9393c), and affects MK183, MK193, MK1E3, and MK1F3.

**Comment by worthbak** [comment]
Ah, good catch - I'll patch and update in the next release.
