### ISSUE TITLE
Custom notification options

### ISSUE THREAD

**Issue by iJas0n** [worthbak/inventory-checker-app#29]
It would be great if there were some custom notification options for when our preferred inventory becomes available, e.g. send an email, run a script, etc. Thanks!

**Comment by worthbak** [comment]
@iJas0n this is an interesting idea, but probably is not something I'll be able to work on in the foreseeable future. You may be better served by the node-script version of this project (which predates the app): https://github.com/worthbak/apple-store-inventory-checker

You could fork that, or just clone it locally and customize the notification code [here](https://github.com/worthbak/apple-store-inventory-checker/blob/main/index.js#L138).
