### ISSUE TITLE
Support for Thailand

### ISSUE THREAD

**Issue by panteparak** [worthbak/inventory-checker-app#32]
Hello,

Great work for creating this app.

It would be great if support for Thailand could be added. I've looked at your source code but do not have the bandwidth nor known Swift enough to be able to test my changes.

However I was able to pinpoint places that need to be added.

(InventoryWatch/Countries.swift)
```
Country Code: TH
Country(
        name: "Thailand",
        storePathComponent: "/th",
        skuCode: "TH",
        altSkuCode: nil
),
```

**Comment by worthbak** [comment]
Fixed in v0.1.2 👍🎉 https://worthbak.github.io/inventory-checker-app/
