### ISSUE TITLE
How does the inventory checker app work?

### ISSUE THREAD

**Issue by YousufSSyed** [worthbak/inventory-checker-app#40]
How is it able to continuously check what devices are in stock at Apple stores?

**Comment by worthbak** [comment]
Apple, perhaps surprisingly, has an open API that its website uses to query for available inventory, either for delivery or in-store pickup. The API is pretty easy to use - see details here in the scripted version of this app: https://github.com/worthbak/apple-store-inventory-checker#apple-store-query-url-pattern

Basically, InventoryWatch passes to this API device SKUs that are known to be stocked by Apple Stores, along with the identifier for a specific Apple Store, and the API responds by noting whether or not each SKU is available for in-store pickup in that store, as well as nearby stores.
