### ISSUE TITLE
Setting "update every" to "never" results in constant refreshing

### ISSUE THREAD

**Issue by garrettreid** [worthbak/inventory-checker-app#43]
When I changed the "update every" part of settings from "1 minute" to "never", the main window refreshed constantly and alerts popped up quickly (my search had matches).

I don't know if my particular settings are necessary to trigger this, but I had "notify only for preferred models" and "only show results for preferred models" checked.

**Comment by worthbak** [comment]
Ah, good catch - patch coming shortly.
