### ISSUE TITLE
App not pulling data

### ISSUE THREAD

**Issue by jhero8** [worthbak/inventory-checker-app#45]
No models available shown though models available through online

**Comment by worthbak** [comment]
Can you give some more info here? Which product and stores are you looking at?

**Comment by jhero8** [comment]
For sure,
![Screen Shot 2022-07-27 at 08 40 14](https://user-images.githubusercontent.com/110104049/181248900-146c8771-121a-4dec-9cb5-4bc42c0bf665.png)

Swapping over to any other models or settings yield the same 'No models available'

**Comment by worthbak** [comment]
Ah, I can repro - looks like Apple tweaked their fulfillment API, which broke my parsing code. I'll ship a patch shortly.

**Comment by worthbak** [comment]
v0.0.9 fixes this issue - you can download here: https://worthbak.github.io/inventory-checker-app/

**Comment by jhero8** [comment]
Super much appreciated! Thank you greatly
