### ISSUE TITLE
M2 (8c CPU, 10c GPU) 16GB/1TB Silver

### ISSUE THREAD

**Issue by andreeastrattner** [worthbak/inventory-checker-app#56]
I would like to submit a PR to add the `M2 (8c CPU, 10c GPU) 16GB/1TB Silver` config for the m2 Macbook Air but how do I go about finding the SKU number for this config?

Thank you!

**Comment by worthbak** [comment]
Unless I'm misunderstanding your question, I believe that config is already in the app? 

<img width="1492" alt="image" src="https://user-images.githubusercontent.com/10028428/187199007-184b1ca4-8674-4e21-8b14-6810f50804b0.png">

**Comment by worthbak** [comment]
Ahhh, I did misunderstand - you're looking for a Silver model. For whatever reason, Apple is not stocking Silver versions of the 16GB/1TB model in-store, and therefore InventoryWatch can't track its availability. Sorry about that!

**Comment by andreeastrattner** [comment]
I see! Thanks for getting back so quickly!
