### ISSUE TITLE
iPhone 14 pro

### ISSUE THREAD

**Issue by zaWarudo99** [worthbak/inventory-checker-app#58]
Could you please add the new iPhone 14 pro Models. thanks

**Comment by worthbak** [comment]
yup, already working on it 👍

**Comment by justinlauffer** [comment]
I sent you a tweet, but happy to help if you'd like. I've gathered most of the SKUs already.

**Comment by worthbak** [comment]
@justinlauffer oh that's rad! I've only pulled together US SKUs - been focusing on some code changes to support both 13 and 14 models. Which countries have you worked on?

**Comment by worthbak** [comment]
I have the app model code updated to account for the new 14 models (I'm keeping the 13/13mini around in the app, but removing the 13 Pro/Pro Max), but still need to compile iPhone model data for non-US countries:

* Canada
* Australia
* Germany
* United Kingdom
* South Korea
* Hong Kong
* France
* Italy
* Japan
* Austria
* Netherlands
* Thailand

If anyone is interested in helping to compile iPhone data for these countries, let me know - I have a script that'll compile the SKU data from the product page on Apple.com, but it just takes a while, and is a bit tedious, to run it for every country individually.

**Comment by purttint** [comment]
Hey worthbak, willing to help for Germany. Am a coding noob though, but if you give me minor instructions I could try something.

**Comment by firenze22** [comment]
Germany iPhone 14/14 Plus

iPhone 14 128GB Midnight | MPUF3ZD/A
iPhone 14 128GB Starlight | MPUR3ZD/A
iPhone 14 128GB Purple | MPV03ZD/A
iPhone 14 128GB (PRODUCT)RED | MPVA3ZD/A
iPhone 14 128GB Blue | MPVN3ZD/A
iPhone 14 256GB Midnight | MPVX3ZD/A
iPhone 14 256GB Starlight | MPW43ZD/A
iPhone 14 256GB Purple | MPWA3ZD/A
iPhone 14 256GB (PRODUCT)RED | MPWH3ZD/A
iPhone 14 256GB Blue | MPWP3ZD/A
iPhone 14 512GB Midnight | MPWW3ZD/A
iPhone 14 512GB Starlight | MPX33ZD/A
iPhone 14 512GB Purple | MPX93ZD/A
iPhone 14 512GB (PRODUCT)RED | MPXG3ZD/A
iPhone 14 512GB Blue | MPXN3ZD/A
iPhone 14 Plus 128GB Midnight | MQ4X3ZD/A
iPhone 14 Plus 128GB Starlight | MQ4Y3ZD/A
iPhone 14 Plus 128GB Purple | MQ503ZD/A
iPhone 14 Plus 128GB (PRODUCT)RED | MQ513ZD/A
iPhone 14 Plus 128GB Blue | MQ523ZD/A
iPhone 14 Plus 256GB Midnight | MQ533ZD/A
iPhone 14 Plus 256GB Starlight | MQ553ZD/A
iPhone 14 Plus 256GB Purple | MQ563ZD/A
iPhone 14 Plus 256GB (PRODUCT)RED | MQ573ZD/A
iPhone 14 Plus 256GB Blue | MQ583ZD/A
iPhone 14 Plus 512GB Midnight | MQ593ZD/A
iPhone 14 Plus 512GB Starlight | MQ5D3ZD/A
iPhone 14 Plus 512GB Purple | MQ5E3ZD/A
iPhone 14 Plus 512GB (PRODUCT)RED | MQ5F3ZD/A
iPhone 14 Plus 512GB Blue | MQ5G3ZD/A

**Comment by JosephNajjar** [comment]
Can't wait till the app gets updated for Canada w/ iPhone 14 Pro

**Comment by worthbak** [comment]
Just posted `v0.1.3` of the app, with full iPhone 14 support 🎉 it can be downloaded here: https://worthbak.github.io/inventory-checker-app/

This is the first time that I've added pre-order products to InventoryWatch, and Apple's API behaves somewhat surprisingly - many iPhone 14 configs currently display as "available", even though they won't become _actually_ available until Friday's launch. I'll keep an eye on this post-launch, as I'm assuming it'll _Just Work_ afterward.
