### ISSUE TITLE
App support for Windows

### ISSUE THREAD

**Issue by Sridhar701Pitt** [worthbak/inventory-checker-app#63]
It would be great if there is support for windows systems. Increases user base.

**Comment by worthbak** [comment]
Writing a Windows version of the app is not in the cards - I don't use Windows, and don't know much about its developer ecosystem. 

That said, the nodeJS version of this app shared most of the core functionality , and others have had success getting it to run on Windows. If you're technically minded, could be worth a shot: https://github.com/worthbak/apple-store-inventory-checker
