### ISSUE TITLE
Notifications don't show location

### ISSUE THREAD

**Issue by ParityError** [worthbak/inventory-checker-app#69]
The notifications don't indicate where the location of the available devices are. It's not very useful omitting the location as you'd need to be staring at the app itself or switch to it every time a notification pops up to see if your closest location has the device. Another solution might be to allow only a specified location to show notifications if preferred perhaps.

**Comment by worthbak** [comment]
Apple's API makes it quite simple to include or exclude results from nearby stores (`&searchNearby=true` or `false`), so I'll update the app to add a toggle for that setting. If you deselect the toggle, you'll only see results (and get notifications) for the selected store. 

That's a quick fix that should get you most of the way there - I'll keep more advanced notification settings in mind for the future.

**Comment by worthbak** [comment]
Added the aforementioned fix in `v0.1.4` 🤘
