### ISSUE TITLE
Display Keyboard language type

### ISSUE THREAD

**Issue by vudzero** [worthbak/inventory-checker-app#8]
Would be nice to have the keyboard type displayed (English, French Canada, ect)

Thanks!

**Comment by worthbak** [comment]
I looked into this a bit, and while it does appear that I can use Apple's retail fulfillment API to query for specific keyboard types, it does _not_ appear that Apple stocks multiple keyboard types in its stores - it seems like they stock a regional default, and everything else is available for online BTO. I'll keep this in mind in the future, but for now, I don't think it's something I'm able to support. I appreciate the suggestion!
