### ISSUE TITLE
Play Notification 

### ISSUE THREAD

**Issue by pistiolasm** [worthbak/inventory-checker-app#82]
We would like to receive a sound/notification when a model becomes available. This way we do not have to keep looking at the application and instead let it run in the background.

**Comment by worthbak** [comment]
Hm, sending local notifications when inventory is found in the background has been a feature of InventoryWatch for a long time - it's a marquee feature on the [homepage](https://worthbak.github.io/inventory-checker-app/):
> InventoryWatch is an app for macOS that monitors local Apple Store inventory and notifies you when your preferred model comes in-stock.

Can you confirm that InventoryWatch has permission to send notifications (in your macOS system preferences), and that `Notify only for preferred models` in InventoryWatch settings is unchecked (or, if it is checked, that you have selected some preferred models)? If so, you should see notifications on your Mac when the app finds inventory.

**Comment by grapeslush** [comment]
Just to add on here, the notifications appear to work for me but they are driving me mad. I get a notification every minute telling me there's no products available. I'm thinking this should really only notify you WHEN there is something available.

I don't see an option to change this unless I'm totally missing something.

**Comment by pistiolasm** [comment]
I checked and did not have notifications turned on. You can select to notify only on items you are tracking. I do not get notifications when something is not available! Thank you and you can close this request!

**Comment by worthbak** [comment]
@pistiolasm nice! glad you got it sorted 👍 

@grapeslush hmm try checking `Notify only for preferred models`: 

<img width="1012" alt="Screen Shot 2022-10-02 at 3 04 21 PM" src="https://user-images.githubusercontent.com/10028428/193476210-18b68c32-78b4-419a-a7ea-5c9d935842e3.png">

That should change your notifications to only notify you when a preferred model is found nearby - that should stop any notifications when no inventory is found.

**Comment by torihiki123** [comment]
Hello, I am able to have alert notification banners, but I was hoping to be able to have Sounds play whenever there is an alert. Is it possible to do that?

**Comment by torihiki123** [comment]
If anyone else wants to get notification sounds, I tried setting `content.sound = UNNotificationSound.default` in NotificationManager.sendNotification() and it worked.
