### ISSUE TITLE
Watch Band Support

### ISSUE THREAD

**Issue by millerd79** [worthbak/inventory-checker-app#85]
Can you please add support for the New watch bands for the Apple Watch Ultra?

**Comment by worthbak** [comment]
I believe all Ultra bands are currently in the app - do you see some that are missing?

**Comment by millerd79** [comment]
The Watch Ultra is listed...but the individual bands that can be purchased
are not.

**Comment by worthbak** [comment]
Ah, I see - adding in all of the band variants is not a high priority at this time (it's a lot of models to track across all of the countries that InventoryWatch supports). However, you can easily add a specific Watch band that you're trying to find via the Custom SKU functionality - see this thread for a bit more info: https://twitter.com/InventoryWatch/status/1579436154134614016

Happy to help you find the SKU value if you'd like!

**Comment by millerd79** [comment]
I found the proper SKU from the Twitter link.  I entered it into the app
under the custom SKU section.

Do I need to click or select anything else? Thanks for your help...

**Comment by worthbak** [comment]
Nope - once it's entered into the Custom SKU field, that model will appear in inventory results under the provided name when found.
