### ISSUE TITLE
Battersea Store

### ISSUE THREAD

**Issue by pinkfizzsocial** [worthbak/inventory-checker-app#90]
Hi will you be adding the new Battersea store to the App?

Also when selecting Milton Keynes, if you click Nearby stores an error comes back.

**Comment by worthbak** [comment]
That store should be in the app soon. And thanks for the bug report re: Milton Keynes - I'll check it out.

**Comment by pinkfizzsocial** [comment]
No - thank you for creating something amazing, it has been so helpful in many ways, really appreciate it.
We are in a forum on MacRumors and a lot of us are using this now with the Hermes Notification manager so we can get the notifications on iOS.

**Comment by worthbak** [comment]
Ah, I appreciate your kind words! Glad to hear InventoryWatch has been helpful to you all, and interesting to hear about Hermes - hadn't come across that before. Feel free to loop me in over at MacRumors if there are any questions - I'm `@worthbak` there (and elsewhere) 👍

**Comment by pinkfizzsocial** [comment]
We get a new thread each year, its mainly to track the despatches but a lot of change our minds and have been using your app to know when stock is available along with monitoring the iUP stock via the Apple Store app.

This thread only opened on 7th September (day of announcement) and now has nearly 16000 posts, lasts years racked up 13500, so we have already well exceeded that!!

**Comment by worthbak** [comment]
> That store should be in the app soon.

Actually, lemme qualify this - AFAICT, if there is going to be a store at Apple's new Battersea campus, it won't open until 2023 (please correct me if I'm wrong). So, I can't add the store to the app just yet. That said, a forthcoming update will load the list of stores dynamically from Apple, so when it opens, it should appear automatically in the app 👍 

Also, thanks for including me in that thread! Very cool community 🥳
