### ISSUE TITLE
Only notify when inventory is found

### ISSUE THREAD

**Issue by danielchasehooper** [worthbak/inventory-checker-app#99]
It's kind of annoying to be notified every time it doesn't find anything. It'd be nice if you could have notifications only for when inventory is found.

**Comment by worthbak** [comment]
That's fair. One workaround is to use the `Notify only for preferred models` option in the app's settings, and select the preferred models you're interested in: 
<img width="900" alt="image" src="https://user-images.githubusercontent.com/10028428/205102560-062dcdff-f321-4817-92ff-8c5abcc6d459.png">

If you use that setting, you'll only receive notifications when those models are found, and should _not_ receive notifications when they are not found.

**Comment by worthbak** [comment]
I'm going to close this issue - please reply if things still aren't working for you 👍
